# Site settings
title:          Read NIME With Me
description:    "Ziyue Piao's Paper Reading Blogs"
url:            "https://piaoziyue.github.io/blog"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Ziyue Piao
  url:          https://piaoziyue.github.io
  email:        piaoziyue@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

baseurl: "" # or "/your-repo-name" if you're hosting on GitHub Pages
paginate: 5


# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale


# Theme
theme:      tale

permalink:  /:year-:month-:day/:title
paginate:   5